### ISSUE TITLE
Can't open the project

### ISSUE THREAD

**Issue by khoadng** [unity-atoms/unity-atoms-examples#2]
Hi, I got this error when trying to open this project in Unity

![Alt text](https://i.imgur.com/TzzSngG.png)

I'm using Unity 2020.2.7f.

<details>
  <summary>Log</summary>
  [Licensing::Module] Channel doesn't exist: "LicenseClient-Admin"
[Licensing::Module] Successfully launched the LicensingClient (PId: 12828)
[Licensing::Module] Successfully connected to LicensingClient on channel: "LicenseClient-Admin" (connect: 0.46s, validation: 0.05s, handshake: 0.50s)
[Licensing::Module] Connected to LicensingClient (PId: 12828, launch time: 0.00, total connection time: 1.00s)
Entitlement-based licensing initiated
[LicensingClient] Licenses updated successfully

LICENSE SYSTEM [202139 18:45:32] Next license update check is after 2021-03-09T11:55:03

LICENSE SYSTEM [202139 18:45:32] Current license is already valid and activated. Skipping license activation process (Provided username/password will be ignored).
Built from '2020.2/staging' branch; Version is '2020.2.7f1 (c53830e277f1) revision 12924976'; Using compiler version '192528614'; Build Type 'Release'
OS: 'Windows 10 Pro; OS build 18363.1379; Version 1909; 64bit' Language: 'en' Physical Memory: 16315 MB
[Licensing::Module] Serial number assigned to: "F4-EG24-4PMK-ZBY9-2DU2-XXXX"
BatchMode: 0, IsHumanControllingUs: 1, StartBugReporterOnCrash: 1, Is64bit: 1, IsPro: 0
[Package Manager] Server::Start -- Port 60794 was selected

 COMMAND LINE ARGUMENTS:
C:\Program Files\Unity\Hub\Editor\2020.2.7f1\Editor\Unity.exe
-projectPath
V:\01_Work\Projects\unity-atoms-examples
Successfully changed project path to: V:\01_Work\Projects\unity-atoms-examples
V:/01_Work/Projects/unity-atoms-examples
Using Asset Import Pipeline V2.
Rebuilding Library because the metadata folder could not be found!

[Package Manager] Done resolving packages in 5.92s seconds
An error occurred while resolving packages:
  Project has invalid dependencies:
    com.unity-atoms.unity-atoms-base-atoms: The file [V:\01_Work\Projects\unity-atoms\Packages\BaseAtoms\package.json] cannot be found
    com.unity-atoms.unity-atoms-core: The file [V:\01_Work\Projects\unity-atoms\Packages\Core\package.json] cannot be found
    com.unity-atoms.unity-atoms-fsm: The file [V:\01_Work\Projects\unity-atoms\Packages\FSM\package.json] cannot be found
    com.unity-atoms.unity-atoms-mobile: The file [V:\01_Work\Projects\unity-atoms\Packages\Mobile\package.json] cannot be found
    com.unity-atoms.unity-atoms-mono-hooks: The file [V:\01_Work\Projects\unity-atoms\Packages\MonoHooks\package.json] cannot be found
    com.unity-atoms.unity-atoms-scene-mgmt: The file [V:\01_Work\Projects\unity-atoms\Packages\SceneMgmt\package.json] cannot be found
    com.unity-atoms.unity-atoms-tags: The file [V:\01_Work\Projects\unity-atoms\Packages\Tags\package.json] cannot be found
    com.unity-atoms.unity-atoms-ui: The file [V:\01_Work\Projects\unity-atoms\Packages\UI\package.json] cannot be found

A re-import of the project may be required to fix the issue or a manual modification of V:/01_Work/Projects/unity-atoms-examples/Packages/manifest.json file.
</details>

**Comment by AdamRamberg** [comment]
Sorry about that. The repo was not 100% setup when you tried it out. It should work now (you need to pull both the main repo and unity-atoms as a sub module to get it to work).
