### ISSUE TITLE
Missing script for HealthListener prefab

### ISSUE THREAD

**Issue by khoadng** [unity-atoms/unity-atoms-examples#4]
The project can run fine, I don't know what is missing though
![Alt text](https://i.imgur.com/TebbRq0.png)

**Comment by AdamRamberg** [comment]
In which scene is this? The HealtListener seems to be fine in the Intro scene in the repo's current state. Can you please verify that this is still an issue.

**Comment by AdamRamberg** [comment]
Can't find this issue in any of the scenes. Closing this issue.
